### ISSUE TITLE
I have to scroll down the screen to be able to save/update a page

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/accelerant-theme#11]
Could we add "update" and "save to exit" buttons to the top, next to "+ new page" ?

When you go in to just enter title and slug you don't want to have to scroll down to the bottom to update/save.

**Comment by designbywilliam** [comment]
Ah, i see you implemented hot keys. Well that is super!:)

I do think clients might like the buttons on top there though:) Hard to get em to use shortcuts sometimes

**Comment by RyanThompson** [comment]
This is how it used to be (top and bottom controls) and I do think I will add it back.. cause aside from the obvious position stuff there is often a view or action button I want visible too.

**Comment by RyanThompson** [comment]
But.. on the flip side.. I REALLY like the cleaner look of not having controls on top..

<img width="1278" alt="screen shot 2017-02-05 at 7 52 45 pm" src="https://cloud.githubusercontent.com/assets/1099967/22632174/b3353ff4-ebdc-11e6-886b-3c1e916d1d95.png">

**Comment by edster** [comment]
I really missed having them up there when I swapped to the new theme

However I now use the shortcuts so it is less of an issue for me.

**Comment by RyanThompson** [comment]
I of course use them too - but a strong argument could be made for buttons alone..

Consider editing a page - save - then it would be nice to have a view button in the bar as well as cancel - so you can quickly open the page to see what you did if not open already.

**Comment by huglester** [comment]
I liked when there was a save button always while you scroll. so if you have long pages, and edit some text in the middle - you do not have to stroll to the bottom to save.

**Comment by RyanThompson** [comment]
Move this to the main repo please.

**Comment by stefanpkc** [comment]
@RyanThompson, the argument of a cleaner look is not valid. It means someone needs to come up with a better design or a solution so it looks clean, but that you still have the controls add the top. Those controls are missing. I will throw it in the slack chat. Perhaps the hive mind has an answer.

Yes... shortcuts are handy. But actions/controls give people also a visual cue of "what's next?"...

**Comment by designbywilliam** [comment]
Im with @stefanpkc . This is a question about usability. Even though i know about and am using hotkeys now. I still find myself sometimes wondering where the actionbuttons are. And if i am, then i am 100% positive my clients will as well.

I can't defend this one saying it's under development or someone thinks it look nicer when they explain they feel this is slowing them down.

**Comment by RyanThompson** [comment]
@designbywilliam fine. OK? Fine.

**Comment by stefanpkc** [comment]
If it looks ugly, someone will clean it up or come up with an idea. Don't worry RyanThompson 😄

**Comment by RyanThompson** [comment]
Lol it's long overdue anyways - bigly needed. Hugely.

**Comment by designbywilliam** [comment]
Everyone hates the giphy master!

**Comment by designbywilliam** [comment]
That being me:)

**Comment by RyanThompson** [comment]
I added this back and I have to say I absolutely hate it.. I think that buttons being at the bottom are:

1.) Common knowledge with end users.

I've personally witnessed multiple training sessions where they completely ignore it because that's not where buttons for a form are commonly found.

2.) Less of an issue with proper form organization.

Currently forms are linear and it can be a pain with them so long. However as we optimize form organization this is going to become less of an issue.

3.) This just looks like dog shit:

<img width="1082" alt="screen shot 2017-03-06 at 11 27 14 pm" src="https://cloud.githubusercontent.com/assets/1099967/23642991/80cbe4e2-02c4-11e7-8dd5-c60b7f27633e.png">

I get that it's usability but .. by principle there is no more or less usability with 1 or 2 control sets. By definition there is the same usability. So it's more of a workflow topic / convenience. I have a hard time taking 5 steps back visually - which also creates mental stress IMO operating the form - just to take what I would consider a half step forward in convenience for an audience that I think won't appreciate it as much as you think.

I am going to place this one on a revisit list. After forms are optimized - we'll listen to the community again for any cries of agony :-P

**Comment by huglester** [comment]
Why not make buttons at top and bottom?

If forms is long- you scroll down a bit- fix small issue. And top buttons are bound to top so easy to click? Like it was earlier?

**Comment by stefanpkc** [comment]
@RyanThompson, what about a sticky? If you scroll down, the buttons become visible at the top. Or let your designer look at it someday. I just can't get used to scrolling down because I had to update the title. I know there's a short key. But half of my clients will never be willing to learn short keys. :(

**Comment by RyanThompson** [comment]
Again this will be less of an issue as forms shrink with improved organization. And I tried the sticky. I hate it. lol

Again.. clients don't think like you do either. We are likely blowing this out of proportion. You're likely the most sophisticated user out of all your clients and you know how to use the hotkey. 

I watch a lot of client training over the shoulder and that's one of the things I was very surprised with (which led me to removing it in the new theme.)

**Comment by RyanThompson** [comment]
Back burner for now.
